### ISSUE TITLE
Generation of BHoM API Docs

### ISSUE THREAD

**Issue by al-fisher** [BHoM/documentation#23] opened 2020-01-12 20:52 UTC
Adding this as an issue on documentation repo @FraserGreenroyd 

As title above - discussed intention to naturally host and update based on master as part of daily alpha release cycle. As well as generate and host specific beta versions.

**Comment by FraserGreenroyd** [comment] 2020-02-07 10:15
Current state of API generation:

 - Object display, showing properties and any method which accepts that object (either by strict object, or by accepting on of its Interface 'tags').
 - Namespace display, showing all objects within that namespace.

Styling/formatting needs work, as well as formalising generation of the data for the API.

@al-fisher it would be good to go through with you at some point and capture the next steps as discrete issues to continue tackling this work.

FYI: @adecler , @IsakNaslundBh , @alelom

**Comment by ebowyer** [comment] 2020-02-07 12:27
Would it be possible to have a search function for the menu from the burger? 
Another thing which I think would be useful is if we can have a way of looking not just at all objects in a category but also all 'structural loading tools/methods' - as I think that may be another way that one would want to search the resource whilst working through.

**Comment by FraserGreenroyd** [comment] 2020-02-07 12:32
> Would it be possible to have a search function for the menu from the burger?
Done

**Comment by FraserGreenroyd** [comment] 2020-02-07 12:58
Discussion with @al-fisher just now.

Order methods by a weighting under the object, starting with the engine most closely related to the object.
E.G. if viewing a BH.oM.Environment.Elements.Panel, see methods from BH.Engine.Environment first before methods from other engines

Add engine methods as an accordion style display, so all the methods don't show at once but are visible on selection by the user.

Add ability to view the API from the perspective of the engines as well (currently we can view from the perspective of the object), so you can view a method and see what inputs it needs (and what types of inputs might be accepted for methods which taken an interface input).
E.G. - "I have an object, what can I do with it" (current implementation) and "I have a method, what do I need to make it work" (new implementation)

Add ability to see which adapters handle a given object - e.g. if viewing Environment.Panel, which adapters can handle this with another accordion view.

**Comment by al-fisher** [comment] 2020-02-07 13:11
🚀

**Comment by FraserGreenroyd** [comment] 2020-02-07 18:20
> Order methods by a weighting under the object, starting with the engine most closely related to the object.

Done

> Add engine methods as an accordion style display, so all the methods don't show at once but are visible on selection by the user.

Done

**Comment by FraserGreenroyd** [comment] 2020-02-10 12:58
> Add ability to view the API from the perspective of the engines as well (currently we can view from the perspective of the object), so you can view a method and see what inputs it needs (and what types of inputs might be accepted for methods which taken an interface input).

Done

**Comment by FraserGreenroyd** [comment] 2020-02-10 13:01
> Add ability to see which adapters handle a given object - e.g. if viewing Environment.Panel, which adapters can handle this with another accordion view.

Hey @alelom - Just to make sure I'm thinking of this the right way for this API stuff, this information is kept in the adapter projects for each adapter isn't it since the refactor? I.E. if I'm pushing or pulling panels, I should see that as methods available in the Adapters Pull.cs/Push.cs right?

**Comment by FraserGreenroyd** [comment] 2020-02-10 14:23
Confirmed with chat with @alelom that above is correct though it's 'Create' and 'Read' methods not Pull/Push.

**Comment by FraserGreenroyd** [comment] 2020-02-11 11:04
On the basis that there is more compliance work on adapters, and further work necessary, I am proposing to park the adapter functionality of the API for now - with a separate issue raised later in the workflow.

I would like to propose closing this issue as 'complete' on the original scope of what we have, with a plan to have further discussions with @al-fisher on hosting the API, and further, discrete, issues raised to resolve outstanding issues (and crucially, styling). @al-fisher would this be ok with you?

**Comment by al-fisher** [comment] 2020-02-11 11:11
Makes sense. 
I would break the Adapter API into (at least)  two phases:
1. Simply reflect a list of Adapters that exist (this in itself can be useful as a list in one place)
2. Reflect the individual CRUD opperations implemented per object type.

Be good to do a meaningful (and somewhat useful) 1. in advance of fully and robustly solving 2.

**Comment by FraserGreenroyd** [comment] 2020-02-11 11:12
Ok great, I'll close this issue for now then, and raise subsequent issues after a detailed chat with you on what the next steps are. I'll pencil something in the calendar shortly :smile:

**Closed by FraserGreenroyd** 2020-02-11 11:12 UTC
Labels: type:documentation, type:feature
